language: python
branches:
  only:
  - master
  - staging
  - stable
install:
- "./.travis/install.sh"
script:
- "./.travis/run.sh"
deploy:
- provider: pypi
  on:
    branch:
    - staging
  server: https://test.pypi.org/legacy/
  distributions: "sdist bdist_wheel"
  skip_existing: true
  user: __token__
  password:
    secure: ejtooENVA7slvUc2UpADwnnMWaDSUE9Yxlk2MYtmsyWu0lYcopUKQlpuwoHKNupV6N58mV903hw7Ya9mn06fdT2pjx9pphFy95/gvnvYWzNQLYYGCruDA70f6ZP5muSjjQvhPPy2L1c2J74VuRDsakY8gE+cax0hGqqtlfEeYQUK8K8l2qH+OE5vDDMCSahGFKOXkBLKSaqSOyi/yYhoEeu6RwCTqVP+NI6U6YnWckLPfpjTJKhXJBiHyjAoXSsjCepKP+kQ5b9QdTMcc/jLU9VQuYCfDMDvHeGZyDebNzNISQLCcUs6MO/BHjU0R8wij2JSHvHyVhjTNoGCQP7xYb5tAEIEOSvWscTqtOcPH1u8uiwKvz+pFPgP0C2v6VeM1phkEgFRiH0l2aIPFA9CDw+YlBJOpqAR6+09Je1llIqxNrCajLLcZW1l00rAqtf4sSPQd+V3aPHjLTkEThKWZg5jbki+fx6M971nfhJkhbt3gBhTqFWEdLGhIUTDgVAQXAbvHx8vwIZ6QEBwcqM06t1DYx0apEy2ngvVok08Umn3Fz0hfA7MD6MuBbyM/FruAe6GXhjLYd4Bsf0ZnUkF6/rCP0Pq68PGdWSYm8r+/9ZUj3gmWpT3iIv2N6BiPM4ZzMb6Fuy5fZv/kDozjSdSOujCFYtdXNeyMZn3rTCa7aU=
- provider: pypi
  on:
    branch:
    - stable
  distributions: "sdist bdist_wheel"
  skip_existing: true
  user: __token__
  password:
    secure: JnaU3xb1UsugqjyZtqJXSICYIsYOo1qDBrfZWiLjvLcRQlZL5WRcdmHo6SQv54mgOmSLk1Xvbh4Acy6Z0LMYPgd7atO8O9oQpJQAH9AG3gt/z2t7l7fL8immgofGDqV7tuGm+eWJyFnF1xgYQljQRImUp+QwzVnNcxUuxtwVsEu2g1sIDurNDXE4FbKYEYfa7KHTHLF2S5utm8849niQlllbv5v5ngNcCzNjw9Ip7+EfmRDMEEwfHN5UkPXrVE/4EmuQrFxZxuBxyo9KPU+eEpERn+46A7ria+FCJAJXey9jgUGGvqsEE/FvUeGYaabk5AB/aTadPU7cQA5x4VSimSK/BnsYOExHNcq02HTzV3Gpd58IcirS4meRQHLo7zGndR+vMF8/IJZzJJKUeo+bq7u+kQ72HeqWP9p67PBo7atcFyjjZz2oogYldfb4Tv/qWJGk4jn/Ty7OUO9QHa9M5yHkjsuC81iWvHSsj56/Sn3uQzqEIRafEmtWSq48YuJyjHSBwA9jM5UxsjUq7nDq5Pv6yLFOV9YBo6pcGBL/wj0xOXR6cDpe8kILegqozPefZI4RiVaP3b5AGDvMFfcA2Jv1q9mzmdvTQ6P7X+lVqMZWNclbxAb+9z3h4wMDjgY3NFZVY5aZtE4ISvTsObOthqOeA0eSV0GJTlOEq+/AuiY=
notifications:
  webhooks:
    urls:
    - https://outlook.office.com/webhook/29ee1687-9c88-4562-98ab-3646bc19dc6f@a73ea017-532f-474b-9c0d-501f28c2f195/TravisCI/64c49d0eceb34b0b84c5b6172d0c6a53/4947dfce-1e6b-4214-a692-f0eee5da19de
    on_success: change
    on_failure: always
    on_start: never
    on_cancel: never
    on_error: always
