sudo: false
language: python

branches:
    only:
        - master

# commands to install dependencies
install:
    - ./.travis/install.sh
# commands to run
script:
    - ./.travis/run.sh

notifications:

webhooks: https://outlook.office.com/webhook/29ee1687-9c88-4562-98ab-3646bc19dc6f@a73ea017-532f-474b-9c0d-501f28c2f195/TravisCI/64c49d0eceb34b0b84c5b6172d0c6a53/4947dfce-1e6b-4214-a692-f0eee5da19de
